### ISSUE TITLE
Sunshine build cannot find suitable cuda compiler

### ISSUE THREAD

**Issue by ReenigneArcher** [LizardByte/pacman-repo#2]
### Describe the Bug

cuda support is not enabled for the Sunshine build. At this point in time, I cannot determine the reason, but passing in the nvcc path manually via `-D CMAKE_CUDA_COMPILER:PATH=/opt/cuda/bin/nvcc` makes cmake fail to compile a simple test program with cuda.

This error does not occur in the upstream build, so not 100% sure what's going on. This issue is mostly for information purposes for users, but if anyone has an idea how to fix it, a PR would be welcomed.

**Comment by kabeer95** [comment]
hey @ReenigneArcher  if its a paid Fix , i can solve this problem
