### ISSUE TITLE
pacman repository sync fails with 404 error for lizardbyte.db

### ISSUE THREAD

**Issue by po4920826** [LizardByte/pacman-repo#5]
### Description

When attempting to synchronize the pacman repositories, the `lizardbyte.db` file fails to download with a 404 error. This prevents the package database from being updated.

### Steps to Reproduce

1. Added the LizardByte repository to `/etc/pacman.conf` as instructed:
    ```
    [lizardbyte]
    SigLevel = Optional
    Server = https://app.lizardbyte.dev/pacman-repo
    ```

2. Ran `sudo pacman -Sy` to update the repository databases.

The following error is encountered:
error: failed retrieving file ‘lizardbyte.db’ from app.lizardbyte.dev : The requested URL returned error: 404 
error: failed to synchronize all databases (failed to retrieve some files)

### Expected Behavior

The `lizardbyte.db` should be downloaded successfully, and the repository should be synchronized without errors.

**Comment by ReenigneArcher** [comment]
Thanks for the report, I'll get it fixed up.

**Comment by ReenigneArcher** [comment]
I put up a fix, after the above mentioned PR is merged, it may take about 15 minutes to update.
