### ISSUE TITLE
Error: failed retrieving file 'sunshine-0.23.1-1-x86_64.pkg.tar.zst.sig' from app.lizardbyte.dev : The requested URL returned error: 404 

### ISSUE THREAD

**Issue by radhaz** [LizardByte/pacman-repo#8]
### Describe the Bug

While installing sunshine via the repo the install fails with this error

```
sunshine-0.23.1-1-x86_64 is up to date
Eerror: failed retrieving file 'sunshine-0.23.1-1-x86_64.pkg.tar.zst.sig' from app.lizardbyte.dev : The requested URL returned error: 404 
warning: failed to retrieve some files 
error: failed to commit transaction (failed to retrieve some files) 
Errors occurred, no packages were upgraded.

Command finished with errors!
```

### Expected Behavior

Expect it to install properly?

### Additional Context

I originally had the sunshine package from the AUR working then migrated to sunshine-bin after recent events. After learning there's now a developer repo for Sunshine I uninstalled the existing package and attempted to install it via the repo and am getting the above error. If it's an operator error or more information is needed just let me know.

**Comment by ReenigneArcher** [comment]
Currently there are no `.sig` files.

Did you add `SigLevel = Optional` ?

**Comment by radhaz** [comment]
> Currently there are no `.sig` files.
> 
> Did you add `SigLevel = Optional` ?

Not that I'm aware of. I added the repository and installed the pacman frontend Octopi (I know it's probably considered bad form but I'm only two weeks into using Arch and still figuring things out as I go) and that's the error I get when I try to install via the repo. 

This is very likely operator error on my part as when I came over to Arch the whole libminiupnpc kerfuffle was ongoing so I tried installing it via the lizardbyte install procedures via the terminal, then the aur bin package, then eventually the aur git package which worked until the bin package was updated and I went over to that. I have likely caused a mess for myself lol, if this issue is only affecting me then I can close it.

**Comment by ReenigneArcher** [comment]
No worries. This is my first attempt at making a pacman repo as well, so I may have missed something. I see some info about signatures [here](https://wiki.archlinux.org/title/Pacman/Package_signing), but I need to research it a little more as I have never signed packages before.

Did you see the instructions in the readme though? https://github.com/LizardByte/pacman-repo?tab=readme-ov-file#installation

Also, as a note, I am working on a small change that will change the ServerUrl to `https://github.com/LizardByte/pacman-repo/releases/latest/download` after https://github.com/LizardByte/pacman-repo/pull/7 is merged.

**Comment by ptr1337** [comment]
> Currently there are no `.sig` files.
> 
> Did you add `SigLevel = Optional` ?

This is very problematic. The package should be properly signed.

**Comment by radhaz** [comment]
> Did you see the instructions in the readme though? https://github.com/LizardByte/pacman-repo?tab=readme-ov-file#installation

Yes that's how I added the repo to be able to install it via octopi

**Comment by ReenigneArcher** [comment]
> This is very problematic. The package should be properly signed.

Any guidance would be appreciated.

**Comment by ptr1337** [comment]
> > This is very problematic. The package should be properly signed.
> 
> Any guidance would be appreciated.

You need to add as secret an GPG Key or equal and then let it sign with:

makepkg --sign 

for example.

**Comment by radhaz** [comment]
> Any guidance would be appreciated.

So I uninstalled everything and removed the entries and redoing the process I was able to get it to work. I see you're having a dialogue with someone regarding best practices so I'm not sure if you want to table that elsewhere and have me close the issue or keep it open for the time being?

**Comment by ReenigneArcher** [comment]
@radhaz Glad it's working! It's okay to leave this issue open until I get package signing implemented.

**Comment by ReenigneArcher** [comment]
Currently the pacman-repo-builder does not sign packages: https://github.com/pacman-repo-builder/pacman-repo-builder/issues/53#issuecomment-1141630841

**Comment by foxler2010** [comment]
> No worries. This is my first attempt at making a pacman repo as well, so I may have missed something. I see some info about signatures [here](https://wiki.archlinux.org/title/Pacman/Package_signing), but I need to research it a little more as I have never signed packages before.
> 
> Did you see the instructions in the readme though? https://github.com/LizardByte/pacman-repo?tab=readme-ov-file#installation
> 
> Also, as a note, I am working on a small change that will change the ServerUrl to `https://github.com/LizardByte/pacman-repo/releases/latest/download` after #7 is merged.

I installed the repo a few days ago and it was working fine until today. When I was updating today, I got a 404 error ehrn downloading the LizardByte repo. After reading your comment, I checked my config, and it was not using the updated URL that was introduced in #7. After changing the URL in pacman.conf, everything is working as it was. Since the repo has to be added manually, any time that configuration has to change, it requires intervention from the user. I was only able to find out about this change by reading this thread, which is not ideal. I would suggest adding something about this change to the README, so that anyone else with this problem can easily figure out the proper steps to take without looking into Issues threads.

**Comment by ReenigneArcher** [comment]
@foxler2010 sorry about that. This repo is only 2 days old, and at the point I made that change it was less than a day old. I can't foresee this URL changing again though, so you should be good for as long as we host this on GitHub.

**Comment by foxler2010** [comment]
Nice. Pretty crazy that I discovered the repo on the day it was created and did not notice.
